title: dadamachines/docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

# Aux links for the upper right navigation
aux_links:
  "Forum":
    - "//forum.dadamachines.com/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
